apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: tars
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 30443 # argocd
        hostPort: 8081
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
