apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: tars
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30443 # argocd
        hostPort: 8080
        protocol: TCP
      - containerPort: 9090 # prometheus
        hostPort: 30000
        protocol: TCP
      # - containerPort: 8080
      #   hostPort: 30301
      #   protocol: TCP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
