apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-example-app
  labels:
    name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-app
  namespace: prometheus-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-example-app
  template:
    metadata:
      labels:
        app: prometheus-example-app
    spec:
      containers:
        - name: prometheus-example-app
          image: quay.io/brancz/prometheus-example-app:v0.3.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  namespace: prometheus-example-app
  labels:
    app: prometheus-example-app
spec:
  selector:
    app: prometheus-example-app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-example-app
  namespace: prometheus-example-app
spec:
  rules:
    - http:
        paths:
          - path: /prometheus-example-app
            pathType: Prefix
            backend:
              service:
                name: prometheus-example-app
                port:
                  number: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-example-app
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: app
  selector:
    matchExpressions:
      - { key: app, operator: Exists }
  namespaceSelector:
    matchNames:
      - prometheus-example-app
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
