defaultRules:
  rules:
    alertmanager: false

alertmanager:
  enabled: false

grafana:
  enabled: true
  ingress:
    enabled: true
    paths:
      - /dashboard

prometheus:
  ingress:
    enabled: true
    paths:
      - /prometheus
