defaultRules:
  rules:
    alertmanager: false

alertmanager:
  enabled: false

grafana:
  enabled: true
  ingress:
    enabled: true
    path: /grafana

prometheus:
  ingress:
    enabled: true
    paths:
      - /prometheus
  service:
    type: NodePort
